cache: bundler
language: ruby
sudo: false

rvm:
  - 2.1

before_install:
  - gem update --system # Need for Ruby 2.5.0. https://github.com/travis-ci/travis-ci/issues/8978
  - gem install bundler -v '~> 1.10'

gemfile:
  - gemfiles/rails_3_2.gemfile
